# Generated by Django 4.2 on 2023-04-10 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compra_date", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("articulos", models.ManyToManyField(to="articulos.articulo")),
            ],
        ),
    ]
