# Generated by Django 4.2 on 2023-04-19 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0003_empleados_tickets_remove_compras_articulos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tickets", options={"verbose_name_plural": "Tickets"},
        ),
        migrations.RemoveField(model_name="tickets", name="id",),
        migrations.AlterField(
            model_name="tickets",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
