# Generated by Django 4.2 on 2023-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=200)),
                ("nombre", models.CharField(max_length=200)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField(help_text="insertar cantidad")),
            ],
        ),
    ]
